export const SLASH_COMMANDS = [
  {
    id: 'h1',
    label: { fr: 'T1', en: 'H1' },
    alias: { fr: ['/t1'], en: ['/h1', '/heading1', '/title1'] },
    description: { fr: 'Titre principal', en: 'Main heading' },
    action: (editor) => editor.chain().focus().toggleHeading({ level: 1 }).run(),
    preview: '<h1 style="font-size:1.5em;">H1</h1>',
  },
  {
    id: 'h2',
    label: { fr: 'T2', en: 'H2' },
    alias: { fr: ['/t2'], en: ['/h2', '/heading2', '/title2'] },
    description: { fr: 'Titre secondaire', en: 'Secondary heading' },
    action: (editor) => editor.chain().focus().toggleHeading({ level: 2 }).run(),
    preview: '<h2 style="font-size:1.2em;">H2</h2>',
  },
  {
    id: 'h3',
    label: { fr: 'T3', en: 'H3' },
    alias: { fr: ['/t3'], en: ['/h3', '/heading3', '/title3'] },
    description: { fr: 'Titre tertiaire', en: 'Tertiary heading' },
    action: (editor) => editor.chain().focus().toggleHeading({ level: 3 }).run(),
    preview: '<h3 style="font-size:1em;">H3</h3>',
  },
  {
    id: 'text',
    label: { fr: 'Texte', en: 'Text' },
    alias: { fr: '/texte', en: '/text' },
    description: { fr: 'Paragraphe simple', en: 'Simple paragraph' },
    action: (editor) => editor.chain().focus().setParagraph().run(),
    preview: '<p>Text</p>',
  },
  {
    id: 'ul',
    label: { fr: 'Liste à puces', en: 'Bulleted list' },
    alias: { fr: '/liste', en: '/list' },
    description: { fr: 'Liste à puces', en: 'Bulleted list' },
    action: (editor) => editor.chain().focus().toggleBulletList().run(),
    preview: '<ul><li>Item</li></ul>',
  },
  {
    id: 'ol',
    label: { fr: 'Liste numérotée', en: 'Numbered list' },
    alias: { fr: '/liste numérotée', en: '/numbered list' },
    description: { fr: 'Liste ordonnée', en: 'Numbered list' },
    action: (editor) => editor.chain().focus().toggleOrderedList().run(),
    preview: '<ol><li>Item</li></ol>',
  },
  {
    id: 'checklist',
    label: { fr: 'Checklist', en: 'Checklist' },
    alias: { fr: '/checklist', en: '/checklist' },
    description: { fr: 'Liste avec cases à cocher', en: 'Checklist' },
    action: (editor) => editor.chain().focus().toggleTaskList().run(),
    preview: '<ul class="checklist"><li><input type="checkbox" /> Task</li></ul>',
  },
  {
    id: 'quote',
    label: { fr: 'Citation', en: 'Quote' },
    alias: { fr: '/citation', en: '/quote' },
    description: { fr: 'Bloc de citation', en: 'Quote block' },
    action: (editor) => editor.chain().focus().toggleBlockquote().run(),
    preview: '<blockquote>Quote</blockquote>',
  },
  {
    id: 'code',
    label: { fr: 'Code', en: 'Code' },
    alias: { fr: '/code', en: '/code' },
    description: { fr: 'Bloc de code', en: 'Code block' },
    action: (editor) => editor.chain().focus().toggleCodeBlock().run(),
    preview: '<pre><code>let x = 42;</code></pre>',
  },
  {
    id: 'separator',
    label: { fr: 'Séparateur', en: 'Separator' },
    alias: { fr: '/séparateur', en: '/separator' },
    description: { fr: 'Trait de séparation', en: 'Horizontal rule' },
    action: (editor) => editor.chain().focus().setHorizontalRule().run(),
    preview: '<hr />',
  },
  {
    id: 'image',
    label: { fr: 'Image', en: 'Image' },
    alias: { fr: '/image', en: '/image' },
    description: { fr: 'Ajouter une image', en: 'Add an image' },
    action: (editor) => editor.chain().focus().setImage({ src: '' }).run(),
    preview: '<img src="https://placehold.co/40x24" alt="Image" />',
  },
  {
    id: 'video',
    label: { fr: 'Vidéo', en: 'Video' },
    alias: { fr: '/vidéo', en: '/video' },
    description: { fr: 'Ajouter une vidéo', en: 'Add a video' },
    action: (editor) => editor.chain().focus().insertContent('<div class="video-embed">Paste a video link here...</div>').run(),
    preview: '<div style="background:#222;color:#fff;padding:4px 8px;border-radius:4px;">Video</div>',
  },
  {
    id: 'ai',
    label: { fr: 'IA', en: 'AI' },
    alias: { fr: '/ai', en: '/ai' },
    description: { fr: 'Demander à l\'IA une action', en: 'Ask AI for an action' },
    action: () => {/* Ouvre un menu IA ou déclenche une action */},
    preview: '<span style="color:#e55a2c;font-weight:bold;">🤖 AI</span>',
  },
  {
    id: 'table',
    label: { fr: 'Tableau', en: 'Table' },
    alias: { fr: '/tableau', en: '/table' },
    description: { fr: 'Insérer un tableau', en: 'Insert a table' },
    action: (editor) => editor.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: true }).run(),
    preview: '<table style="border:1px solid #ccc;"><tr><td>Cell</td></tr></table>',
  },
  {
    id: 'callout',
    label: { fr: 'Appel', en: 'Callout' },
    alias: { fr: '/appel', en: '/callout' },
    description: { fr: 'Bloc avec icône', en: 'Callout box' },
    action: (editor) => editor.chain().focus().insertContent('<div class="callout">💡 Callout</div>').run(),
    preview: '<div class="callout">💡 Callout</div>',
  },
  {
    id: 'link',
    label: { fr: 'Lien', en: 'Link' },
    alias: { fr: '/lien', en: '/link' },
    description: { fr: 'Insérer un lien', en: 'Insert a link' },
    action: (editor) => editor.chain().focus().setLink({ href: '' }).run(),
    preview: '<a href="#">Link</a>',
  },
  {
    id: 'draft',
    label: { fr: 'Brouillon', en: 'Draft' },
    alias: { fr: '/brouillon', en: '/draft' },
    description: { fr: 'Marquer comme brouillon', en: 'Mark as draft' },
    action: (editor) => editor.chain().focus().insertContent('<span class="draft">Draft</span>').run(),
    preview: '<span class="draft" style="color:#aaa;">Draft</span>',
  },
  {
    id: 'task-list',
    label: { fr: 'Liste de tâches', en: 'Todo list' },
    alias: { fr: '/liste de tâches', en: '/todo' },
    description: { fr: 'Checklist interactive', en: 'Interactive checklist' },
    action: (editor) => editor.chain().focus().toggleTaskList().run(),
    preview: '<ul class="task-list"><li><input type="checkbox" /> Task</li></ul>',
  },
  {
    id: 'emoji',
    label: { fr: 'Emoji', en: 'Emoji' },
    alias: { fr: '/emoji', en: '/emoji' },
    description: { fr: 'Choisir un émoji', en: 'Pick an emoji' },
    action: () => {/* Ouvre un picker d'emoji */},
    preview: '<span style="font-size:1.2em;">��</span>',
  },
]; 